### ISSUE TITLE
Couldn't send AdditionalOptions

### ISSUE THREAD

**Issue by Qfrost911** [NewWorldComingSoon/llvm-msvc-issues#1]
I use Visual Studio 2019 and select ”LLVM-MSVC_v142_KernelMode“ mode. I set some additionaloptions in Project->C/C++-> AdditionalOptions
![image](https://user-images.githubusercontent.com/58380176/168058258-e5d0abca-b6f1-4010-8372-74f55f4e2f38.png)
 But it is not effective.

I print the MSBuild command, my additionaloptions was not send to clang-cl.exe
![image](https://user-images.githubusercontent.com/58380176/168059381-e3cd5abe-f094-4530-85ab-ebc387918a98.png)

I select “LLVM-MSVC_v142” mode, the MSBuild command is right. So I think problem only occurs in mode “LLVM-MSVC_v142_KernelMode”

**Comment by gmh5225** [comment]
llvm-msvc does not come with obfuscation currently.
you should add obfuscation by yourself or wait for my later update.
In addition, you can go ahead and learn how to write a new pass. 
[New Pass Manager](https://llvm.org/docs/NewPassManager.html)

**Comment by Qfrost911** [comment]
I modify the regedit to set my OLLVM dir. I mean I set additional options, such as "-mllvm -fla",  in VS-Projects->C++->command is not effective when I use  ”LLVM-MSVC_v142_KernelMode“ mode.  Because, the MSBuild command made by tools chains didn't contain my additional options.

**Comment by gmh5225** [comment]
Now fixed in [v1.4](https://github.com/NewWorldComingSoon/llvm-msvc-build/releases/tag/llvm-msvc-build-v1.4)
