### ISSUE TITLE
[clang] illegal character encoding

### ISSUE THREAD

**Issue by gmh5225** [NewWorldComingSoon/llvm-msvc-issues#12]
```C++
 MessageBoxW(0, 0, L"你好", 0);
 MessageBoxW(0, 0, L"こんにちは", 0);
```
->>>>>>>>>>>>>>>>>>>>>>>>>>>
`error : illegal character encoding in string literal`

**Comment by Qfrost911** [comment]
![QQ截图20221126230200](https://user-images.githubusercontent.com/58380176/204095454-6c62f750-2076-42cc-bfda-0ecd9b1d25a6.jpg)
I can not reproduce this problem using LLVM16 + VS2019 + LLVM-MSVC

**Comment by gmh5225** [comment]
What is the encoding of your soure file?
UTF-8 is OK.

**Comment by gmh5225** [comment]
DONE
https://github.com/NewWorldComingSoon/llvm-msvc/commit/5ab74d10b991908d076127ca515ba224d220e159
