### ISSUE TITLE
no such file or directory: '/d1nodatetime' 

### ISSUE THREAD

**Issue by Qfrost911** [NewWorldComingSoon/llvm-msvc-issues#2]
I update llvm-msvc to v1.4. ,but it occurs a new error.
I modify the "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\LLVM\LLVM-MSVC" to my LLVM 12.0, and use  "LLVM-MSVC_v142_KernelMode" mode to compile driver. 
![image](https://user-images.githubusercontent.com/58380176/168514499-45a9aed7-b5ce-4263-a830-ed8ad5b7cc13.png)

I try to replace clang-cl11.exe and lld-link.exe of llvm-msvc with my LLVM Dir, the errors still exists.

**Comment by gmh5225** [comment]
this won't work, you need to use llvm-msvc not other version
or you guys can modify the code yourself [manually ](https://github.com/NewWorldComingSoon/llvm-msvc/commit/e0c6b99374dfcbb73854bb3fe8afccf91f0a6809)
