### ISSUE TITLE
多线程编译

### ISSUE THREAD

**Issue by icls1337** [NewWorldComingSoon/llvm-msvc-issues#30]
使用Intel C++ Compiler 2022编译时发现会自动使用全部核心
编译[nana](https://github.com/cnjinhao/nana)
llvm-msvc:
02:47.996
intel c++ compiler 2022:
14.018

**Comment by gmh5225** [comment]
Although clang-cl does not currently support `/MP`.  It was required in msvc.
I will look at this in the following days.

**Comment by gmh5225** [comment]
Done
https://github.com/backengineering/llvm-msvc/issues/17
