### ISSUE TITLE
` -mno-sse` sse disable invalid 

### ISSUE THREAD

**Issue by Chordp** [NewWorldComingSoon/llvm-msvc-issues#5]
` -mno-sse` sse disable invalid 
Compile still have sse instructions

**Comment by gmh5225** [comment]
because I've forced the `sse `setting to be compatible with MSVC
see follow:
https://github.com/NewWorldComingSoon/llvm-msvc/blob/main/clang/tools/driver/driver.cpp#L387

**Comment by gmh5225** [comment]
Now you can use `-mno-sse3` or `-mno-ssse3` or `-mno-sse4.1` to disable SSE instructions.
https://github.com/NewWorldComingSoon/llvm-msvc/commit/f1d6ae309cf1d50436a29aaeb1598abcc5187978
