### ISSUE TITLE
llvm-msvc 开发驱动,对函数静态对象的初始化有页故障问题

### ISSUE THREAD

**Issue by fgmailbox** [NewWorldComingSoon/llvm-msvc-issues#57]
llvm-msvc 开发驱动,对函数静态对象的初始化有页故障问题,但是微软官方的wdk开发工具没有类似的问题

**Comment by fgmailbox** [comment]
"llvm-msvc development driver has page fault issues with static object initialization, but Microsoft's official WDK development tool does not have similar problems."

**Comment by gmh5225** [comment]
感谢反馈, 是否可以提供一份源代码以及蓝屏的dump文件

**Comment by fgmailbox** [comment]
![image](https://github.com/NewWorldComingSoon/llvm-msvc-issues/assets/10250531/eee3ea94-7791-4862-bbc4-da2d7a2f9add)

**Comment by fgmailbox** [comment]
[CactiWall.zip](https://github.com/NewWorldComingSoon/llvm-msvc-issues/files/11785492/CactiWall.zip)

**Comment by fgmailbox** [comment]
void func()
{

static int cnt = 0;
    PVOID p_cnt = &cnt;
    auto pMdl = IoAllocateMdl(p_cnt, PAGE_SIZE, FALSE, FALSE, NULL);

    MmBuildMdlForNonPagedPool(pMdl);

    // 锁定页面
    MmProbeAndLockPages(pMdl, KernelMode, IoModifyAccess);

    PVOID pLockedBuffer = MmGetSystemAddressForMdlSafe(pMdl, NormalPagePriority);

    ProbeForWrite(pLockedBuffer, PAGE_SIZE - 16, 8);

    ProbeForWrite(p_cnt, PAGE_SIZE - 16, 8);

}

这一段话,就会蓝屏

**Comment by fgmailbox** [comment]
dump 文件传不上来,有90M

**Comment by gmh5225** [comment]
测试仓库: https://github.com/gmh5225/test-llvm-msvc-issue-57

MSVC: https://github.com/gmh5225/test-llvm-msvc-issue-57/tree/main/bin/VS2022-MSVC
LLVM: https://github.com/gmh5225/test-llvm-msvc-issue-57/tree/main/bin/VS2022-MSVC

测试结论: 均会蓝屏 

您需要等待一下2.6的版本，2.5的版本存在 section 属性不对的问题

**Comment by fgmailbox** [comment]
在这里页故障 :"static PNPAGED_LOOKASIDE_LIST pNpageList = "

static PNPAGED_LOOKASIDE_LIST pNpageList = init_lookaside_private<PNPAGED_LOOKASIDE_LIST,SIZE, TAG, ARENA>(); 

static PNPAGED_LOOKASIDE_LIST pNpageList = init_lookaside_private<PNPAGED_LOOKASIDE_LIST,256, 'CACT', NonPagedPool>();


 template <typename LookAsideType, ULONG SIZE, ULONG TAG, ULONG ARENA>
LookAsideType
init_lookaside_private()
{

    __try
    {

        if constexpr (std::is_same_v<LookAsideType, PNPAGED_LOOKASIDE_LIST>)
        {
            aux_::auto_irql_raiser irql(DISPATCH_LEVEL);


            static NPAGED_LOOKASIDE_LIST npageList{0};

            ExInitializeNPagedLookasideList(
                &npageList,
                // NULL, NULL,
                &mem_alloc,
                //ExFreePool,
                &dealloc<SIZE, TAG, ARENA>,
                0,
                SIZE,
                TAG,
                0
                //(8192) / SIZE
            );
            return &npageList;
        }
        else if constexpr (std::is_same_v<LookAsideType, PPAGED_LOOKASIDE_LIST>)
        {

            static PAGED_LOOKASIDE_LIST pageList{0};
            aux_::auto_irql_raiser irql(APC_LEVEL);
            ExInitializePagedLookasideList(
                &pageList,
                // NULL, NULL,
                &mem_alloc,
                //&ExFreePool,
                &dealloc<SIZE, TAG, ARENA>,
                0,
                SIZE,
                TAG,
                // (8192) / SIZE
                0);
            return &pageList;
        }
    }
    __except (EXCEPTION_EXECUTE_HANDLER)
    { // User opted to ignore the breakpoint
        LOG("初始化 LookasideList 失败");
        ASSERTMSG((PSTR) "初始化 LookasideList 失败,发生异常", false);
        return nullptr;
    }
};

**Comment by fgmailbox** [comment]
template <typename LookAsideType, ULONG SIZE, ULONG TAG, ULONG ARENA>
LookAsideType
init_lookaside_private()
{

__try
{

    if constexpr (std::is_same_v<LookAsideType, PNPAGED_LOOKASIDE_LIST>)
    {
        aux_::auto_irql_raiser irql(DISPATCH_LEVEL);


        static NPAGED_LOOKASIDE_LIST npageList{0};

        ExInitializeNPagedLookasideList(
            &npageList,
            // NULL, NULL,
            &mem_alloc,
            //ExFreePool,
            &dealloc<SIZE, TAG, ARENA>,
            0,
            SIZE,
            TAG,
            0
            //(8192) / SIZE
        );
        return &npageList;
    }
    else if constexpr (std::is_same_v<LookAsideType, PPAGED_LOOKASIDE_LIST>)
    {

        static PAGED_LOOKASIDE_LIST pageList{0};
        aux_::auto_irql_raiser irql(APC_LEVEL);
        ExInitializePagedLookasideList(
            &pageList,
            // NULL, NULL,
            &mem_alloc,
            //&ExFreePool,
            &dealloc<SIZE, TAG, ARENA>,
            0,
            SIZE,
            TAG,
            // (8192) / SIZE
            0);
        return &pageList;
    }
}
__except (EXCEPTION_EXECUTE_HANDLER)
{ // User opted to ignore the breakpoint
    LOG("初始化 LookasideList 失败");
    ASSERTMSG((PSTR) "初始化 LookasideList 失败,发生异常", false);
    return nullptr;
}
};


void testfunc()
{
static PNPAGED_LOOKASIDE_LIST pNpageList = init_lookaside_private<PNPAGED_LOOKASIDE_LIST,256, 'CACT', NonPagedPool>();
}；
你可以用这两个函数测试,需要c++17以上支持

**Comment by fgmailbox** [comment]
大哥,问题依然存在页故障,建议你用以下函数试试
template <typename LookAsideType, ULONG SIZE, ULONG TAG, ULONG ARENA>
LookAsideType
init_lookaside_private()
{

__try
{

if constexpr (std::is_same_v<LookAsideType, PNPAGED_LOOKASIDE_LIST>)
{
    aux_::auto_irql_raiser irql(DISPATCH_LEVEL);


    static NPAGED_LOOKASIDE_LIST npageList{0};

    ExInitializeNPagedLookasideList(
        &npageList,
        // NULL, NULL,
        &mem_alloc,
        //ExFreePool,
        &dealloc<SIZE, TAG, ARENA>,
        0,
        SIZE,
        TAG,
        0
        //(8192) / SIZE
    );
    return &npageList;
}
else if constexpr (std::is_same_v<LookAsideType, PPAGED_LOOKASIDE_LIST>)
{

    static PAGED_LOOKASIDE_LIST pageList{0};
    aux_::auto_irql_raiser irql(APC_LEVEL);
    ExInitializePagedLookasideList(
        &pageList,
        // NULL, NULL,
        &mem_alloc,
        //&ExFreePool,
        &dealloc<SIZE, TAG, ARENA>,
        0,
        SIZE,
        TAG,
        // (8192) / SIZE
        0);
    return &pageList;
}
}
__except (EXCEPTION_EXECUTE_HANDLER)
{ // User opted to ignore the breakpoint
LOG("初始化 LookasideList 失败");
ASSERTMSG((PSTR) "初始化 LookasideList 失败,发生异常", false);
return nullptr;
}
};

void testfunc()
{
static PNPAGED_LOOKASIDE_LIST pNpageList = init_lookaside_private<PNPAGED_LOOKASIDE_LIST,256, 'CACT', NonPagedPool>();
}；
你可以用这两个函数测试,需要c++17以上支持
