### ISSUE TITLE
Add lld for llvm-msvc-build release?

### ISSUE THREAD

**Issue by icls1337** [NewWorldComingSoon/llvm-msvc-issues#6]

**Comment by Qfrost911** [comment]
https://github.com/gmh5225/llvm-msvc-compatibility#5lldcoffdrivercpp

**Comment by gmh5225** [comment]
This is achievable. The general idea is to generate the binary and then recalculate the checksum before outputting it

**Comment by gmh5225** [comment]
DONE
https://github.com/NewWorldComingSoon/llvm-msvc/commit/36baefb934595e9e8733cde7cbf20360b02047f5
