### ISSUE TITLE
lvm-msvc-kernelmode 2.7 开发驱动,对函数静态自定义类型对象的初始化仍然有页故障问题 #60

### ISSUE THREAD

**Issue by fgmailbox** [NewWorldComingSoon/llvm-msvc-issues#61]
`
template < ULONG tag >
class TestClass
{
	int value = 0;
public:
	TestClass(int value_ = 0) : value(value_){};
};

template < ULONG tag >
void test()
{

#ifdef __clang__
#pragma data_seg(".data")
#endif
	static int cnt { [](int val) { return val; }(tag) };
	int *p_cnt = &cnt;

	using TestClass = TestClass<tag>;
	// 以下用llvm-msvc-kernelmode 2.7 开发驱动,必定会发生页故障, 
	// 这在内核开发有点难以接受
	// 但是wdk驱动开发工具是不会发生的,
	static TestClass testClass1(tag+100);

	static  TestClass testClass2(tag + 200);

	static  TestClass testClass4 {[](int val) { return val; }(tag)};
#if 0  //def __clang__
    //内核线程局部变量可能会有问题,有最好,没有也没有关系,可以将这段代码注解起来
	static thread_local int thr_cnt = [](auto val) { return val; }(tag + 1000);
	int *p_thr_cnt = &thr_cnt;
	static thread_local int thr_cnt2 = tag + 1000;
	int *p_thr_cnt2 = &thr_cnt2;

	static thread_local TestClass testClass3(tag + 300);
#endif

#ifdef __clang__
#pragma data_seg()
#endif
}

extern "C"
NTSTATUS
DriverEntry( IN PDRIVER_OBJECT driverObject, IN PUNICODE_STRING registryPath )
{
	test<128>();
}
`

**Comment by fgmailbox** [comment]
[llvm-msvc-kernel-driver.zip](https://github.com/NewWorldComingSoon/llvm-msvc-issues/files/11924355/llvm-msvc-kernel-driver.zip)

**Comment by fgmailbox** [comment]
[llvm-msvc-kernel-driver.zip](https://github.com/NewWorldComingSoon/llvm-msvc-issues/files/11924356/llvm-msvc-kernel-driver.zip)

迫切希望你能解决这个问题,因为WDK工具编译我的驱动release版会搞死编译器,只能编译debug版本

**Comment by gmh5225** [comment]
哥，看到了，不用发那么多issue。你先把你代码整理下。
可以借助markdown语法，使用 2个 ``` 把代码包裹起来。这样看起来舒服一些。

**Comment by fgmailbox** [comment]
有压缩文件的代码呀

**Comment by gmh5225** [comment]
可以试试 v2.8
https://github.com/NewWorldComingSoon/llvm-msvc-build/releases/download/llvm-msvc-build-v2.8/llvm-msvc_X86_64_installer.exe
